version: '3'

networks:
  frontend:
  backend:

services:
  goskel:
    networks:
      - backend
    image: goskel:latest

  grpcwebproxy:
    networks:
      - frontend
      - backend
    image: grpc-web:grpcwebproxy
    build:
      context: ./
      dockerfile: ./dockerdeps/grpcwebproxy/Dockerfile
    ports:
      - "8080:8080"
    links:
      - goskel