version: '3.8'

networks:
  frontend:
  backend:

services:
  #### frontend
  goskel-web:
    networks:
      - frontend
    image: goskel-web:latest
    build:
      context: ./web/
      dockerfile: ./web/Dockerfile
    ports:
      - "3000:3000"
    tty: true

  #### backend
  goskel:
    networks:
      - backend
    image: goskel:latest

  grpcwebproxy:
    networks:
      - frontend
      - backend
    image: grpc-web:grpcwebproxy
    build:
      context: ./
      dockerfile: ./dockerdeps/grpcwebproxy/Dockerfile
    ports:
      - "8080:8080"
    links:
      - goskel