version: '3.8'

networks:
  frontend:
  backend:


services:
  #### frontend
  goskel-web:
    networks:
      - frontend
    image: goskel-web:latest
    depends_on:
      - goskel
      - grpcwebproxy
    build:
      context: ./web/
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    tty: true

  #### backend
  goskel:
    networks:
      - backend
    image: goskel:latest
    build:
      context: ./
      dockerfile: ./Dockerfile

  grpcwebproxy:
    networks:
      - frontend
      - backend
    image: grpc-web:grpcwebproxy
    depends_on:
      - goskel
    build:
      context: ./dockerdeps/grpcwebproxy
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    links:
      - goskel
